#!/usr/bin/env python3
"""Parse a ChamberMaster MemberResource XML export into SQL upserts.

Usage:
  python3 supabase/scripts/seed_members_from_xml.py /path/to/WKCCActiveMembers.html \\
    > /tmp/chamber_members_seed.sql
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path


def tag(block: str, name: str) -> str | None:
    match = re.search(rf"<{name}\b[^>]*>(.*?)</{name}\s*>", block, flags=re.S)
    if not match:
        return None
    return (
        re.sub(r"\s+", " ", match.group(1))
        .replace("&amp;", "&")
        .replace("&apos;", "'")
        .strip()
    )


def sql_str(value: str | None) -> str:
    if value is None or value == "":
        return "NULL"
    return "'" + value.replace("'", "''") + "'"


def sql_ts(value: str | None) -> str:
    if not value:
        return "NULL"
    return f"'{value}'::timestamptz"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("xml_path", type=Path)
    args = parser.parse_args()

    text = args.xml_path.read_text(errors="ignore")
    blocks = re.findall(
        r"<MemberResource\b[^>]*>(.*?)</MemberResource\s*>",
        text,
        flags=re.S,
    )

    print("-- Generated by supabase/scripts/seed_members_from_xml.py")
    print(
        "insert into public.chamber_members "
        "(cm_id, name, display_name, email, status, level, "
        "membership_established, drop_date, slug, display_flags, raw, synced_at)"
    )
    print("values")

    values: list[str] = []
    for block in blocks:
        cm_id = int(tag(block, "Id") or "0")
        name = tag(block, "Name") or f"Member {cm_id}"
        display = tag(block, "DisplayName") or name
        email = tag(block, "Email")
        email_norm = email.lower().strip() if email else None
        status = tag(block, "Status") or "0"
        level = tag(block, "Level")
        established = tag(block, "MembershipEstablished")
        drop = tag(block, "DropDate")
        slug = tag(block, "Slug")
        flags = tag(block, "DisplayFlags") or ""
        raw = {
            "Id": cm_id,
            "Name": name,
            "DisplayName": display,
            "Email": email,
            "Status": status,
            "Level": level,
            "MembershipEstablished": established,
            "DropDate": drop,
            "Slug": slug,
            "DisplayFlags": flags,
        }
        values.append(
            "  ("
            f"{cm_id}, {sql_str(name)}, {sql_str(display)}, {sql_str(email_norm)}, "
            f"{sql_str(status)}, {sql_str(level)}, {sql_ts(established)}, {sql_ts(drop)}, "
            f"{sql_str(slug)}, {sql_str(flags)}, {sql_str(json.dumps(raw))}::jsonb, now())"
        )

    print(",\n".join(values))
    print("on conflict (cm_id) do update set")
    print("  name = excluded.name,")
    print("  display_name = excluded.display_name,")
    print("  email = excluded.email,")
    print("  status = excluded.status,")
    print("  level = excluded.level,")
    print("  membership_established = excluded.membership_established,")
    print("  drop_date = excluded.drop_date,")
    print("  slug = excluded.slug,")
    print("  display_flags = excluded.display_flags,")
    print("  raw = excluded.raw,")
    print("  synced_at = excluded.synced_at;")
    print(f"-- rows: {len(values)}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
