-- Import Membership Type + Website from chamber listing CSV.
-- website_url only filled when null (member edits preserved).
-- Generated 215 email-matched updates from supabase/data/chamber_member_listing.csv

UPDATE public.chamber_members SET membership_type = 'Basic', website_url = COALESCE(website_url, 'http://www.alacarteinc.com') WHERE lower(email) = 'alacarte.catering@sbcglobal.net';
UPDATE public.chamber_members SET membership_type = 'Platinum', website_url = COALESCE(website_url, 'http://www.chaletnursery.com') WHERE lower(email) = 'michik@chaletnursery.com';
UPDATE public.chamber_members SET membership_type = 'Basic', website_url = COALESCE(website_url, 'http://www.c-lace.com') WHERE lower(email) = 'larisa@c-lace.com';
UPDATE public.chamber_members SET membership_type = 'Platinum', website_url = COALESCE(website_url, 'http://www.pawdr.com') WHERE lower(email) = 'mlockhart@pawdr.com';
UPDATE public.chamber_members SET membership_type = 'Silver', website_url = COALESCE(website_url, 'http://www.convitocafeandmarket.com') WHERE lower(email) = 'convitocafe@gmail.com';
UPDATE public.chamber_members SET membership_type = 'Basic', website_url = COALESCE(website_url, 'http://www.danielsautowilmette.com') WHERE lower(email) = 'danielsautowil@sbcglobal.net';
UPDATE public.chamber_members SET membership_type = 'Platinum', website_url = COALESCE(website_url, 'http://www.degiuliodesign.com') WHERE lower(email) = 'ccostello@degiuliodesign.com';
UPDATE public.chamber_members SET membership_type = 'Platinum', website_url = COALESCE(website_url, 'http://www.bylinebank.com') WHERE lower(email) = 'kogasawara@bylinebank.com';
UPDATE public.chamber_members SET membership_type = 'Silver', website_url = COALESCE(website_url, 'http://www.fuenferjewelers.com') WHERE lower(email) = 'nfuenfer@sbcglobal.net';
UPDATE public.chamber_members SET membership_type = 'Silver', website_url = COALESCE(website_url, 'http://greenbayanimalhospital.com/') WHERE lower(email) = 'nharas@vetcor.com';
UPDATE public.chamber_members SET membership_type = 'Basic', website_url = COALESCE(website_url, 'http://www.hanigs.com') WHERE lower(email) = 'wilmette@hanigs.com';
UPDATE public.chamber_members SET membership_type = 'Basic', website_url = COALESCE(website_url, 'http://www.ibji.com') WHERE lower(email) = 'lmjensen@ibji.com';
UPDATE public.chamber_members SET membership_type = 'Silver', website_url = COALESCE(website_url, 'http://www.nsautomotive.net') WHERE lower(email) = 'northshoreauto@comcast.net';
UPDATE public.chamber_members SET membership_type = 'Basic', website_url = COALESCE(website_url, 'http://www.irvings.com') WHERE lower(email) = 'andy@irvings.com';
UPDATE public.chamber_members SET membership_type = 'Silver', website_url = COALESCE(website_url, 'http://www.plazaorthodontics.com') WHERE lower(email) = 'janet@plazaorthodontics.com';
UPDATE public.chamber_members SET membership_type = 'Silver', website_url = COALESCE(website_url, 'http://www.kenilworthparkdistrict.org') WHERE lower(email) = 'jkiwala@kpdistrict.org';
UPDATE public.chamber_members SET membership_type = 'Platinum', website_url = COALESCE(website_url, 'http://www.kerriganplumbing.com') WHERE lower(email) = 'mkerrigan@kerriganplumbing.com';
UPDATE public.chamber_members SET membership_type = 'Platinum', website_url = COALESCE(website_url, 'http://www.lambrechtsjewelers.com') WHERE lower(email) = 'info@lambrechtsjewelers.com';
UPDATE public.chamber_members SET membership_type = 'Non-Profit', website_url = COALESCE(website_url, 'http://www.michiganshores.org') WHERE lower(email) = 'communications@michiganshores.org';
UPDATE public.chamber_members SET membership_type = 'Basic', website_url = COALESCE(website_url, 'http://www.midcentralprinting.com') WHERE lower(email) = 'mcpm1910@yahoo.com';
UPDATE public.chamber_members SET membership_type = 'Basic', website_url = COALESCE(website_url, 'http://newvisionopticalwilmette.net') WHERE lower(email) = 'newvopt@gmail.com';
UPDATE public.chamber_members SET membership_type = 'Non-Profit', website_url = COALESCE(website_url, 'http://www.oakton.edu') WHERE lower(email) = 'emcdonag@oakton.edu';
UPDATE public.chamber_members SET membership_type = 'Gold', website_url = COALESCE(website_url, 'http://www.pansdocs.com') WHERE lower(email) = 'info@pansdocs.com';
UPDATE public.chamber_members SET membership_type = 'Platinum', website_url = COALESCE(website_url, 'http://www.plazadelago.com') WHERE lower(email) = 'brittany.mundarain@wsdevelopment.com';
UPDATE public.chamber_members SET membership_type = 'Platinum', website_url = COALESCE(website_url, 'http://www.inbk.com/') WHERE lower(email) = 'eric.hubbard@inbk.com';
UPDATE public.chamber_members SET membership_type = 'Non-Profit', website_url = COALESCE(website_url, 'http://www.rdpanthers.org') WHERE lower(email) = 'marketing@rdpanthers.org';
UPDATE public.chamber_members SET membership_type = 'Basic', website_url = COALESCE(website_url, 'http://www.ridgeviewgrill.com') WHERE lower(email) = 'ridgeviewgrill@sbcglobal.net';
UPDATE public.chamber_members SET membership_type = 'Non-Profit', website_url = COALESCE(website_url, 'http://www.womansclubofwilmette.org') WHERE lower(email) = 'communications@womansclubofwilmette.org';
UPDATE public.chamber_members SET membership_type = 'Basic', website_url = COALESCE(website_url, 'http://shawneeservicecenter.com') WHERE lower(email) = 'shawneegarage@comcast.net';
UPDATE public.chamber_members SET membership_type = 'Basic' WHERE lower(email) = 'sweetsshop@sbcglobal.net';
UPDATE public.chamber_members SET membership_type = 'Silver', website_url = COALESCE(website_url, 'http://www.terryah.com') WHERE lower(email) = 'terry_ah@sbcglobal.net';
UPDATE public.chamber_members SET membership_type = 'Basic', website_url = COALESCE(website_url, 'http://www.vestorrealty.com') WHERE lower(email) = 'vrcappr@sbcglobal.net';
UPDATE public.chamber_members SET membership_type = 'Municipality', website_url = COALESCE(website_url, 'http://www.wilmette.com') WHERE lower(email) = 'hallgrene@wilmette.com';
UPDATE public.chamber_members SET membership_type = 'Basic', website_url = COALESCE(website_url, 'http://wilmetteautobody.com') WHERE lower(email) = 'glen@wilmetteautobody.com';
UPDATE public.chamber_members SET membership_type = 'Basic', website_url = COALESCE(website_url, 'http://www.wilmettesportshop.com/') WHERE lower(email) = 'wilmettesportshop@comcast.net';
UPDATE public.chamber_members SET membership_type = 'Chamber of Commerce', website_url = COALESCE(website_url, 'http://www.wilmettekenilworth.org') WHERE lower(email) = 'info@wilmettekenilworth.com';
UPDATE public.chamber_members SET membership_type = 'Non-Profit', website_url = COALESCE(website_url, 'http://www.wilmettehistory.org') WHERE lower(email) = 'museum@wilmette.com';
UPDATE public.chamber_members SET membership_type = 'Silver', website_url = COALESCE(website_url, 'http://www.luckeplumbing.com') WHERE lower(email) = 'wilplumb@sbcglobal.net';
UPDATE public.chamber_members SET membership_type = 'Silver', website_url = COALESCE(website_url, 'http://www.wilmettepark.org') WHERE lower(email) = 'clindgren@wilpark.org';
UPDATE public.chamber_members SET membership_type = 'Gold', website_url = COALESCE(website_url, 'http://www.wilmettelibrary.info') WHERE lower(email) = 'aauston@wilmettelibrary.info';
UPDATE public.chamber_members SET membership_type = 'Non-Profit', website_url = COALESCE(website_url, 'http://www.wilmettetheatre.com') WHERE lower(email) = 'info@wilmettetheatre.com';
UPDATE public.chamber_members SET membership_type = 'Basic', website_url = COALESCE(website_url, 'http://www.greenmanit.com') WHERE lower(email) = 'dlee@greenmanit.com';
UPDATE public.chamber_members SET membership_type = 'Basic', website_url = COALESCE(website_url, 'http://www.wilmettemaids.com') WHERE lower(email) = 'info@wilmettemaids.com';
UPDATE public.chamber_members SET membership_type = 'Platinum', website_url = COALESCE(website_url, 'http://www.nscbank.com') WHERE lower(email) = 'mdonnell@nscbank.com';
UPDATE public.chamber_members SET membership_type = 'Basic', website_url = COALESCE(website_url, 'http://www.benedettodental.com') WHERE lower(email) = 'benedettodental@gmail.com';
UPDATE public.chamber_members SET membership_type = 'Basic', website_url = COALESCE(website_url, 'http://www.acfom.com') WHERE lower(email) = 'jason@acfom.com';
UPDATE public.chamber_members SET membership_type = 'Basic', website_url = COALESCE(website_url, 'http://www.westendflorist.com') WHERE lower(email) = 'ehoffmanwest@ameritech.net';
UPDATE public.chamber_members SET membership_type = 'Non-Profit', website_url = COALESCE(website_url, 'http://www.lssi.org/service/ShoreLinePlace.aspx') WHERE lower(email) = 'shore.line@lssi.org';
UPDATE public.chamber_members SET membership_type = 'Non-Profit', website_url = COALESCE(website_url, 'http://www.ronaldknox.org') WHERE lower(email) = 'office_manager@ronaldknox.org';
UPDATE public.chamber_members SET membership_type = 'Gold', website_url = COALESCE(website_url, 'http://pediatric-dentistry.org/') WHERE lower(email) = 'smile@pediatric-dentistry.org';
UPDATE public.chamber_members SET membership_type = 'Basic', website_url = COALESCE(website_url, 'http://www.raynordoor.com') WHERE lower(email) = 'john@raynordoor.com';
UPDATE public.chamber_members SET membership_type = 'Basic' WHERE lower(email) = 'sfeldman@northshore.net';
UPDATE public.chamber_members SET membership_type = 'Basic', website_url = COALESCE(website_url, 'http://www.egortho.com') WHERE lower(email) = 'frontdesk@egortho.com';
UPDATE public.chamber_members SET membership_type = 'Basic', website_url = COALESCE(website_url, 'http://www.thebottleshop.net') WHERE lower(email) = 'amy@thebottleshop.net';
UPDATE public.chamber_members SET membership_type = 'Non-Profit', website_url = COALESCE(website_url, 'http://www.bakerdemschool.org') WHERE lower(email) = 'communications@bakerdemschool.org';
UPDATE public.chamber_members SET membership_type = 'Non-Profit', website_url = COALESCE(website_url, 'http://wilmetterotary.org/') WHERE lower(email) = 'clubrotarywilmette@gmail.com';
UPDATE public.chamber_members SET membership_type = 'Basic', website_url = COALESCE(website_url, 'http://www.litigatorsinc.net') WHERE lower(email) = 'litigatorsinc@msn.com';
UPDATE public.chamber_members SET membership_type = 'Basic', website_url = COALESCE(website_url, 'http://www.mcclellanortho.com/') WHERE lower(email) = 'cher.phillips@shoreviewortho.com';
UPDATE public.chamber_members SET membership_type = 'Basic', website_url = COALESCE(website_url, 'http://www.toddmarkman.com') WHERE lower(email) = 'todd@toddmarkman.com';
UPDATE public.chamber_members SET membership_type = 'Basic', website_url = COALESCE(website_url, 'https://midwestcertified.com/') WHERE lower(email) = 'britney@midwestga.com';
UPDATE public.chamber_members SET membership_type = 'Non-Profit', website_url = COALESCE(website_url, 'http://www.gogreenwilmette.org') WHERE lower(email) = 'info@gogreenwilmette.org';
UPDATE public.chamber_members SET membership_type = 'Non-Profit', website_url = COALESCE(website_url, 'https://newtrierdemocrats.org/') WHERE lower(email) = 'team@newtrierdemocrats.org';
UPDATE public.chamber_members SET membership_type = 'Basic', website_url = COALESCE(website_url, 'https://johnmillenhardware.com') WHERE lower(email) = 'dibmillen@gmail.com';
UPDATE public.chamber_members SET membership_type = 'Basic', website_url = COALESCE(website_url, 'https://thekey.com/locations/illinois/chicago') WHERE lower(email) = 'nhopkins@thekey.com';
UPDATE public.chamber_members SET membership_type = 'Basic', website_url = COALESCE(website_url, 'http://www.whlee.com') WHERE lower(email) = 'whleenorth@whlee.com';
UPDATE public.chamber_members SET membership_type = 'Basic', website_url = COALESCE(website_url, 'http://www.business.comcast.com') WHERE lower(email) = 'chaitenya_goshalia@cable.comcast.com';
UPDATE public.chamber_members SET membership_type = 'Municipality', website_url = COALESCE(website_url, 'http://www.vok.org') WHERE lower(email) = 'info@vok.org';
UPDATE public.chamber_members SET membership_type = 'Platinum', website_url = COALESCE(website_url, 'http://www.atproperties.com') WHERE lower(email) = 'carrietarzon@atproperties.com';
UPDATE public.chamber_members SET membership_type = 'Basic', website_url = COALESCE(website_url, 'http://www.andersonbuilt.com') WHERE lower(email) = 'pa@andersonbuilt.com';
UPDATE public.chamber_members SET membership_type = 'Non-Profit', website_url = COALESCE(website_url, 'http://www.chabadwilmette.com') WHERE lower(email) = 'rabbi@chabadwilmette.com';
UPDATE public.chamber_members SET membership_type = 'Non-Profit', website_url = COALESCE(website_url, 'http://www.newtriertownship.com') WHERE lower(email) = 'lhopkins@newtriertownship.com';
UPDATE public.chamber_members SET membership_type = 'Basic', website_url = COALESCE(website_url, 'http://www.wilmettefootcare.com') WHERE lower(email) = 'doctor@wellfoot.com';
UPDATE public.chamber_members SET membership_type = 'Silver', website_url = COALESCE(website_url, 'http://www.northshoremusicwilmette.com') WHERE lower(email) = 'nsmwilmette@gmail.com';
UPDATE public.chamber_members SET membership_type = 'Non-Profit', website_url = COALESCE(website_url, 'http://www.musictheaterworks.com') WHERE lower(email) = 'kdougan@musictheaterworks.org';
UPDATE public.chamber_members SET membership_type = 'Silver', website_url = COALESCE(website_url, 'http://studionorthacademy.com') WHERE lower(email) = 'snapwilmette@gmail.com';
UPDATE public.chamber_members SET membership_type = 'Basic', website_url = COALESCE(website_url, 'http://www.yellowbirdstore.com') WHERE lower(email) = 'yellowbirdstore@sbcglobal.net';
UPDATE public.chamber_members SET membership_type = 'Non-Profit', website_url = COALESCE(website_url, 'http://www.musicinst.org') WHERE lower(email) = 'efusco@musicinst.org';
UPDATE public.chamber_members SET membership_type = 'Basic', website_url = COALESCE(website_url, 'http://www.mathnasium.com/kenilworth') WHERE lower(email) = 'jsteve@schoolhouse4math.com';
UPDATE public.chamber_members SET membership_type = 'Silver', website_url = COALESCE(website_url, 'http://johnplunkettinteriors.com') WHERE lower(email) = 'office@johnplunkettinteriors.com';
UPDATE public.chamber_members SET membership_type = 'Silver', website_url = COALESCE(website_url, 'http://marriott.com/chiwl') WHERE lower(email) = 'koconnell@zmchotels.com';
UPDATE public.chamber_members SET membership_type = 'Platinum', website_url = COALESCE(website_url, 'http://www.charleshutchinsonlaw.com') WHERE lower(email) = 'charles@charleshutchinsonlaw.com';
UPDATE public.chamber_members SET membership_type = 'Silver', website_url = COALESCE(website_url, 'http://hubbahubbawilmette.com') WHERE lower(email) = 'hubbahubba.wilmette@gmail.com';
UPDATE public.chamber_members SET membership_type = 'Silver', website_url = COALESCE(website_url, 'http://bellatileandstone.com') WHERE lower(email) = 'missy@bellatileandstone.com';
UPDATE public.chamber_members SET membership_type = 'Platinum', website_url = COALESCE(website_url, 'http://www.nsago.com') WHERE lower(email) = 'lasaleh60@gmail.com';
UPDATE public.chamber_members SET membership_type = 'Silver', website_url = COALESCE(website_url, 'http://www.bannerliteracy.com') WHERE lower(email) = 'terrie.briggs@bannerliteracy.com';
UPDATE public.chamber_members SET membership_type = 'Non-Profit', website_url = COALESCE(website_url, 'https://newtrierconnect.org') WHERE lower(email) = 'mayere@newtrier.k12.il.us';
UPDATE public.chamber_members SET membership_type = 'Non-Profit', website_url = COALESCE(website_url, 'http://www.strogerabbey.org') WHERE lower(email) = 'raphael10@aol.com';
UPDATE public.chamber_members SET membership_type = 'Silver', website_url = COALESCE(website_url, 'http://www.smilindental.com') WHERE lower(email) = 'smilin@smilindental.com';
UPDATE public.chamber_members SET membership_type = 'Silver', website_url = COALESCE(website_url, 'http://aperryhomes.com') WHERE lower(email) = 'aperryhomes@gmail.com';
UPDATE public.chamber_members SET membership_type = 'Silver', website_url = COALESCE(website_url, 'http://www.napolitapizza.com') WHERE lower(email) = 'josh@vandalaybrands.com';
UPDATE public.chamber_members SET membership_type = 'Basic', website_url = COALESCE(website_url, 'http://www.kurv.com') WHERE lower(email) = 'rabbimartyn@gmail.com';
UPDATE public.chamber_members SET membership_type = 'Silver', website_url = COALESCE(website_url, 'http://www.redspadeenvironments.com') WHERE lower(email) = 'skmyers@redspadeenvironments.com';
UPDATE public.chamber_members SET membership_type = 'Basic', website_url = COALESCE(website_url, 'https://www.linkedin.com/in/heatherhehman') WHERE lower(email) = 'heather@efficiencymarketingandpublicity.com';
UPDATE public.chamber_members SET membership_type = 'Basic', website_url = COALESCE(website_url, 'https://www.grottocom.com') WHERE lower(email) = 'kim@grottocom.com';
UPDATE public.chamber_members SET membership_type = 'Basic', website_url = COALESCE(website_url, 'http://www.ginorthshore.com') WHERE lower(email) = 'info@ginorthshore.com';
UPDATE public.chamber_members SET membership_type = 'Silver', website_url = COALESCE(website_url, 'http://www.torinoramen.com') WHERE lower(email) = 'info@torinoramen.com';
UPDATE public.chamber_members SET membership_type = 'Basic' WHERE lower(email) = 'askgroup2020@gmail.com';
UPDATE public.chamber_members SET membership_type = 'Basic', website_url = COALESCE(website_url, 'http://www.theresidencesofwilmette.com/') WHERE lower(email) = 'residencesofwilmette@rmk.com';
UPDATE public.chamber_members SET membership_type = 'Basic', website_url = COALESCE(website_url, 'http://www.otofloat.com') WHERE lower(email) = 'heather@otofloat.com';
UPDATE public.chamber_members SET membership_type = 'Basic', website_url = COALESCE(website_url, 'https://lightonanxiety.com/') WHERE lower(email) = 'hello@lightonanxiety.com';
UPDATE public.chamber_members SET membership_type = 'Platinum', website_url = COALESCE(website_url, 'http://www.secureil.com') WHERE lower(email) = 'charlie@secureil.com';
UPDATE public.chamber_members SET membership_type = 'Platinum', website_url = COALESCE(website_url, 'https://www.bellacosajewelers.com/') WHERE lower(email) = 'hello@mybella.com';
UPDATE public.chamber_members SET membership_type = 'Non-Profit', website_url = COALESCE(website_url, 'http://www.ywca-ens.org/shop') WHERE lower(email) = 'ywshop@ywca-ens.org';
UPDATE public.chamber_members SET membership_type = 'Silver', website_url = COALESCE(website_url, 'http://osteostrongwilmette.me') WHERE lower(email) = 'wilmette@osteostrong.me';
UPDATE public.chamber_members SET membership_type = 'Basic', website_url = COALESCE(website_url, 'https://savantwealth.com') WHERE lower(email) = 'mward@savantwealth.com';
UPDATE public.chamber_members SET membership_type = 'Basic', website_url = COALESCE(website_url, 'http://www.bigcityoptical.com') WHERE lower(email) = 'vision@bigcityoptical.com';
UPDATE public.chamber_members SET membership_type = 'Silver', website_url = COALESCE(website_url, 'http://www.pescaderofish.com') WHERE lower(email) = 'josh@vandalaybrands.com';
UPDATE public.chamber_members SET membership_type = 'Basic', website_url = COALESCE(website_url, 'http://www.insuranceppl.com') WHERE lower(email) = 'alexandra.eidenberg@insuranceppl.com';
UPDATE public.chamber_members SET membership_type = 'Basic', website_url = COALESCE(website_url, 'http://www.mylapels.com/locations/wilmette/') WHERE lower(email) = 'lapels.wilmette@gmail.com';
UPDATE public.chamber_members SET membership_type = 'Non-Profit', website_url = COALESCE(website_url, 'http://newtrier.k12.il.us') WHERE lower(email) = 'sallyp@nths.net';
UPDATE public.chamber_members SET membership_type = 'Platinum', website_url = COALESCE(website_url, 'http://www.optimaverdana.com') WHERE lower(email) = 'burnhama@optima.inc';
UPDATE public.chamber_members SET membership_type = 'Non-Profit', website_url = COALESCE(website_url, 'http://www.faithhopeschool.org/') WHERE lower(email) = 'lgarrett@faithhopeschool.org';
UPDATE public.chamber_members SET membership_type = 'Silver', website_url = COALESCE(website_url, 'http://www.canninglegal.com') WHERE lower(email) = 'chris@canninglegal.com';
UPDATE public.chamber_members SET membership_type = 'Platinum', website_url = COALESCE(website_url, 'http://www.sophiasteak.com') WHERE lower(email) = 'info@sophiasteak.com';
UPDATE public.chamber_members SET membership_type = 'Basic' WHERE lower(email) = 'p.hansen@comcast.net';
UPDATE public.chamber_members SET membership_type = 'Basic', website_url = COALESCE(website_url, 'http://www.bleacherssports.com') WHERE lower(email) = 'bleacherz@aol.com';
UPDATE public.chamber_members SET membership_type = 'Silver', website_url = COALESCE(website_url, 'https://wilmette.artisseniorliving.com/') WHERE lower(email) = 'treich@artismgmt.com';
UPDATE public.chamber_members SET membership_type = 'Silver', website_url = COALESCE(website_url, 'http://www.1mmspa.com') WHERE lower(email) = 'concierge@1mmspa.com';
UPDATE public.chamber_members SET membership_type = 'Basic', website_url = COALESCE(website_url, 'https://www.optimumfitnessformula7.com/joining') WHERE lower(email) = 'optimumfitnessformula@gmail.com';
UPDATE public.chamber_members SET membership_type = 'Non-Profit', website_url = COALESCE(website_url, 'http://www.ourplaceofnewtrier.org') WHERE lower(email) = 'info@ourplaceofnewtrier.org';
UPDATE public.chamber_members SET membership_type = 'Basic', website_url = COALESCE(website_url, 'http://sulackinsurance.com') WHERE lower(email) = 'nathan@sulackinsurance.com';
UPDATE public.chamber_members SET membership_type = 'Basic', website_url = COALESCE(website_url, 'http://www.plumgroveinc.com') WHERE lower(email) = 'sharon@plumgroveinc.com';
UPDATE public.chamber_members SET membership_type = 'Non-Profit', website_url = COALESCE(website_url, 'http://www.actorstrainingcenter.org') WHERE lower(email) = 'info@actorstrainingcenter.com';
UPDATE public.chamber_members SET membership_type = 'Silver', website_url = COALESCE(website_url, 'https://www.gigglesgiraffes.com/') WHERE lower(email) = 'denisehelms@comcast.net';
UPDATE public.chamber_members SET membership_type = 'Basic', website_url = COALESCE(website_url, 'https://www.sophiasestatesales.com') WHERE lower(email) = 'sophia@sophiadubrul.com';
UPDATE public.chamber_members SET membership_type = 'Platinum', website_url = COALESCE(website_url, 'https://buckrussells.com/') WHERE lower(email) = 'nicole@ballyhoohospitality.com';
UPDATE public.chamber_members SET membership_type = 'Non-Profit', website_url = COALESCE(website_url, 'https://northshoreexchange.org/') WHERE lower(email) = 'wendy@northshoreexchange.org';
UPDATE public.chamber_members SET membership_type = 'Non-Profit', website_url = COALESCE(website_url, 'https://www.goramblers.org/') WHERE lower(email) = 'legan@loy.org';
UPDATE public.chamber_members SET membership_type = 'Basic', website_url = COALESCE(website_url, 'https://www.cookcountyil.gov/all-people/scott-britton') WHERE lower(email) = 'liz.polmanski@cookcountyil.gov';
UPDATE public.chamber_members SET membership_type = 'Non-Profit', website_url = COALESCE(website_url, 'http://trinitywilmette.com') WHERE lower(email) = 'trinityinfo@trinitywilmette.org';
UPDATE public.chamber_members SET membership_type = 'Basic', website_url = COALESCE(website_url, 'http://www.trgheatingandcooling.com') WHERE lower(email) = 'service@therayesgroup.com';
UPDATE public.chamber_members SET membership_type = 'Silver', website_url = COALESCE(website_url, 'http://aaserviceco.com') WHERE lower(email) = 'smansfield@aaserviceco.com';
UPDATE public.chamber_members SET membership_type = 'Basic', website_url = COALESCE(website_url, 'https://ajhorner.evrealestate.com') WHERE lower(email) = 'chicagonorthshore@evrealestate.com';
UPDATE public.chamber_members SET membership_type = 'Basic', website_url = COALESCE(website_url, 'https://www.northshoreloyalty.com/') WHERE lower(email) = 'ron@northshoreloyalty.com';
UPDATE public.chamber_members SET membership_type = 'Platinum', website_url = COALESCE(website_url, 'http://ballyhoohospitality.com') WHERE lower(email) = 'info@ballyhoohospitality.com';
UPDATE public.chamber_members SET membership_type = 'Non-Profit', website_url = COALESCE(website_url, 'https://www.lwvwilmette.org/') WHERE lower(email) = 'lwvwilmetteevents@gmail.com';
UPDATE public.chamber_members SET membership_type = 'Non-Profit', website_url = COALESCE(website_url, 'http://youthchoraltheater.org') WHERE lower(email) = 'info@youthchoraltheater.org';
UPDATE public.chamber_members SET membership_type = 'Basic', website_url = COALESCE(website_url, 'http://www.valleylodgetavern.com') WHERE lower(email) = 'valleylodgeevents@gmail.com';
UPDATE public.chamber_members SET membership_type = 'Basic', website_url = COALESCE(website_url, 'https://vibratoboutique.com') WHERE lower(email) = 'vibratoboutique@hotmail.com';
UPDATE public.chamber_members SET membership_type = 'Silver', website_url = COALESCE(website_url, 'http://www.abbottpainting.com') WHERE lower(email) = 'rob@abbottpainting.com';
UPDATE public.chamber_members SET membership_type = 'Silver', website_url = COALESCE(website_url, 'https://www.pella.com/locations/il/northfield/') WHERE lower(email) = 'lackowskibc@pella.com';
UPDATE public.chamber_members SET membership_type = 'Platinum', website_url = COALESCE(website_url, 'https://www.wayfair.com/m/wilmette') WHERE lower(email) = 'jjacksonwhitman@wayfair.com';
UPDATE public.chamber_members SET membership_type = 'Basic', website_url = COALESCE(website_url, 'https://tomchowaniec.focalpointcoaching.com') WHERE lower(email) = 'tchowaniec@focalpointcoaching.com';
UPDATE public.chamber_members SET membership_type = 'Silver', website_url = COALESCE(website_url, 'http://thepatriciangallery.com') WHERE lower(email) = 'info@thepatriciangallery.com';
UPDATE public.chamber_members SET membership_type = 'Non-Profit', website_url = COALESCE(website_url, 'http://www.ysgn.org') WHERE lower(email) = 'whitney.madeen@ysgn.org';
UPDATE public.chamber_members SET membership_type = 'Silver', website_url = COALESCE(website_url, 'http://proself-storage.com') WHERE lower(email) = 'fuhler@refinedrealtyllc.com';
UPDATE public.chamber_members SET membership_type = 'Gold', website_url = COALESCE(website_url, 'http://www.styleexteriors.com') WHERE lower(email) = 'office@styleexteriors.com';
UPDATE public.chamber_members SET membership_type = 'Silver', website_url = COALESCE(website_url, 'http://greatwater360autocare.com') WHERE lower(email) = 'jkowalski@greatwatergarages.com';
UPDATE public.chamber_members SET membership_type = 'Basic', website_url = COALESCE(website_url, 'https://www.clubwilmette.com') WHERE lower(email) = 'grafeedie@tellyourstoryinc.com';
UPDATE public.chamber_members SET membership_type = 'Basic', website_url = COALESCE(website_url, 'https://www.northshoregaragedoors.com/') WHERE lower(email) = 'office@northshoregaragedoors.com';
UPDATE public.chamber_members SET membership_type = 'Basic', website_url = COALESCE(website_url, 'https://www.friogelato.com/') WHERE lower(email) = 'info@friogelato.com';
UPDATE public.chamber_members SET membership_type = 'Basic', website_url = COALESCE(website_url, 'https://evadeans.com/') WHERE lower(email) = 'downer.jordana@gmail.com';
UPDATE public.chamber_members SET membership_type = 'Basic', website_url = COALESCE(website_url, 'https://lightupyourholidays.com/') WHERE lower(email) = 'kelly@lightupyourholidays.com';
UPDATE public.chamber_members SET membership_type = 'Platinum', website_url = COALESCE(website_url, 'https://0ecff09.rcomhost.com/') WHERE lower(email) = 'craigscottoptics@gmail.com';
UPDATE public.chamber_members SET membership_type = 'Platinum', website_url = COALESCE(website_url, 'https://mazmezgrill.com/') WHERE lower(email) = 'mazmezgrill@outlook.com';
UPDATE public.chamber_members SET membership_type = 'Silver', website_url = COALESCE(website_url, 'https://epochnorthshore.com/') WHERE lower(email) = 'hello@epochnorthshore.com';
UPDATE public.chamber_members SET membership_type = 'Platinum', website_url = COALESCE(website_url, 'http://www.edensplaza.com') WHERE lower(email) = 'edensplaza@wsdevelopment.com';
UPDATE public.chamber_members SET membership_type = 'Platinum', website_url = COALESCE(website_url, 'http://elizabethgriffingifts.com') WHERE lower(email) = 'elizabethgriffin1132@gmail.com';
UPDATE public.chamber_members SET membership_type = 'Silver', website_url = COALESCE(website_url, 'http://www.suvchicagolimo.com') WHERE lower(email) = 'info@suvchicagolimo.com';
UPDATE public.chamber_members SET membership_type = 'Basic', website_url = COALESCE(website_url, 'http://floorcoveringsinternational.com') WHERE lower(email) = 'om.eggener@fcifloors.com';
UPDATE public.chamber_members SET membership_type = 'Non-Profit', website_url = COALESCE(website_url, 'http://kenilworthhistory.org') WHERE lower(email) = 'info@kenilworthhistory.org';
UPDATE public.chamber_members SET membership_type = 'Basic', website_url = COALESCE(website_url, 'https://bigblueswimschool.com/') WHERE lower(email) = 'kedelstein@bigblueswimschool.com';
UPDATE public.chamber_members SET membership_type = 'Basic', website_url = COALESCE(website_url, 'https://www.jamesmartinassociates.com/') WHERE lower(email) = 'l.cuna@jamesmartinassociates.com';
UPDATE public.chamber_members SET membership_type = 'Silver', website_url = COALESCE(website_url, 'http://www.chicagoracoons.com') WHERE lower(email) = 'info@chicagoracoons.com';
UPDATE public.chamber_members SET membership_type = 'Silver', website_url = COALESCE(website_url, 'http://chicagodermatologyphysicians.com') WHERE lower(email) = 'clinical-admin@chicagodermatologyphysicians.com';
UPDATE public.chamber_members SET membership_type = 'Platinum', website_url = COALESCE(website_url, 'http://www.ddkkitchens.com') WHERE lower(email) = 'dbertucci@ddkkitchens.com';
UPDATE public.chamber_members SET membership_type = 'Gold', website_url = COALESCE(website_url, 'http://freedomhomecare.net') WHERE lower(email) = 'lbogira@freedomhomecare.net';
UPDATE public.chamber_members SET membership_type = 'Platinum', website_url = COALESCE(website_url, 'https://www.onecompassionatehomecare.com/') WHERE lower(email) = 'info@onecompassionate.com';
UPDATE public.chamber_members SET membership_type = 'Basic', website_url = COALESCE(website_url, 'http://www.nicolejonesphotography.com') WHERE lower(email) = 'nicole@nicolejonesphotography.com';
UPDATE public.chamber_members SET membership_type = 'Basic', website_url = COALESCE(website_url, 'http://pioneerconcierge.com') WHERE lower(email) = 'pioneerconciergemedicine@gmail.com';
UPDATE public.chamber_members SET membership_type = 'Silver', website_url = COALESCE(website_url, 'http://theupsstore.com') WHERE lower(email) = 'store1119@theupsstore.com';
UPDATE public.chamber_members SET membership_type = 'Non-Profit', website_url = COALESCE(website_url, 'https://hadleyhelps.org/') WHERE lower(email) = 'info@hadleyhelps.org';
UPDATE public.chamber_members SET membership_type = 'Basic', website_url = COALESCE(website_url, 'http://locations.thepaperstore.com') WHERE lower(email) = 'gabrielle.lewis@tpsgroupholdings.com';
UPDATE public.chamber_members SET membership_type = 'Silver', website_url = COALESCE(website_url, 'http://luxrallytravel.com') WHERE lower(email) = 'katerina.kaplich@luxrallytravel.com';
UPDATE public.chamber_members SET membership_type = 'Basic', website_url = COALESCE(website_url, 'https://www.adamczykfinehomes.com/') WHERE lower(email) = 'elliot@adamczykfinehomes.com';
UPDATE public.chamber_members SET membership_type = 'Silver', website_url = COALESCE(website_url, 'http://eggharborcafe.com') WHERE lower(email) = 'brandi.walt@eggharborcafe.com';
UPDATE public.chamber_members SET membership_type = 'Basic' WHERE lower(email) = 'henryrawner@yahoo.com';
UPDATE public.chamber_members SET membership_type = 'Non-Profit', website_url = COALESCE(website_url, 'http://nscds.org') WHERE lower(email) = 'communications@nscds.org';
UPDATE public.chamber_members SET membership_type = 'Basic', website_url = COALESCE(website_url, 'http://www.chicagoartisanmarket.com') WHERE lower(email) = 'jjsmith@stylechicago.com';
UPDATE public.chamber_members SET membership_type = 'Basic' WHERE lower(email) = 'erika@smallcheval.com';
UPDATE public.chamber_members SET membership_type = 'Silver', website_url = COALESCE(website_url, 'https://forefrontdermatology.com/location/wilmette-il-60091/') WHERE lower(email) = 'paige.mcmorris@forefrontderm.com';
UPDATE public.chamber_members SET membership_type = 'Silver', website_url = COALESCE(website_url, 'http://junechildrensshop.com') WHERE lower(email) = 'info@junechildrensshop.com';
UPDATE public.chamber_members SET membership_type = 'Silver', website_url = COALESCE(website_url, 'https://sites.google.com/kcoombespt.com/katharine-coombes/home?authuser=0') WHERE lower(email) = 'kcoombes@kcoombespt.com';
UPDATE public.chamber_members SET membership_type = 'Basic', website_url = COALESCE(website_url, 'http://lindenjewelers.com') WHERE lower(email) = 'seth@lindenjewelers.com';
UPDATE public.chamber_members SET membership_type = 'Basic' WHERE lower(email) = 'lheusdens@icloud.com';
UPDATE public.chamber_members SET membership_type = 'Silver', website_url = COALESCE(website_url, 'https://www.fredastaire.com/wilmette/') WHERE lower(email) = 'wilmette@fredastaire.com';
UPDATE public.chamber_members SET membership_type = 'Basic', website_url = COALESCE(website_url, 'http://shoptaliaboutique.com') WHERE lower(email) = 'info@taliaboutique.com';
UPDATE public.chamber_members SET membership_type = 'Silver', website_url = COALESCE(website_url, 'http://thehenryatharmswoolds.com') WHERE lower(email) = 'henryatharmswoods@knck.io';
UPDATE public.chamber_members SET membership_type = 'Basic' WHERE lower(email) = 'ebony@heartautocare.com';
UPDATE public.chamber_members SET membership_type = 'Non-Profit', website_url = COALESCE(website_url, 'http://www.havenforyouth.org') WHERE lower(email) = 'adina@havenforyouth.org';
UPDATE public.chamber_members SET membership_type = 'Basic' WHERE lower(email) = 'admin@careathomeproviders.com';
UPDATE public.chamber_members SET membership_type = 'Basic' WHERE lower(email) = 'brett@campfiresauna.com';
UPDATE public.chamber_members SET membership_type = 'Silver' WHERE lower(email) = 'mgreenberg@forwardfocusmed.com';
UPDATE public.chamber_members SET membership_type = 'Basic' WHERE lower(email) = 'ramaa.krishnan@yahoo.com';
UPDATE public.chamber_members SET membership_type = 'Basic', website_url = COALESCE(website_url, 'https://www.culturalcare.com/lcc/lmurlick/') WHERE lower(email) = 'laurie.murlick@lcc.culturalcare.com';
UPDATE public.chamber_members SET membership_type = 'Basic' WHERE lower(email) = 'northshorebarrington@soccerstars.com';
UPDATE public.chamber_members SET membership_type = 'Silver', website_url = COALESCE(website_url, 'http://www.ChicNoel.com') WHERE lower(email) = 'diane@chicnoel.com';
UPDATE public.chamber_members SET membership_type = 'Basic', website_url = COALESCE(website_url, 'http://www.seejanesparkle.com') WHERE lower(email) = 'cso@seejanesparkle.com';
UPDATE public.chamber_members SET membership_type = 'Silver', website_url = COALESCE(website_url, 'http://inviahcare.com') WHERE lower(email) = 'natallia.panysh@inviacare.com';
UPDATE public.chamber_members SET membership_type = 'Basic' WHERE lower(email) = 'tjot847@gmail.com';
UPDATE public.chamber_members SET membership_type = 'Silver' WHERE lower(email) = 'chad@lift-chicago.com';
UPDATE public.chamber_members SET membership_type = 'Basic' WHERE lower(email) = 'andrew.gardner@edwardjones.com';
UPDATE public.chamber_members SET membership_type = 'Basic', website_url = COALESCE(website_url, 'http://www.tellyourstoryinc.com') WHERE lower(email) = 'grafeedie@tellyourstoryinc.com';
UPDATE public.chamber_members SET membership_type = 'Basic' WHERE lower(email) = 'e@firesideplanning.com';
UPDATE public.chamber_members SET membership_type = 'Basic' WHERE lower(email) = 'bluerosecompany@gmail.com';
UPDATE public.chamber_members SET membership_type = 'Basic', website_url = COALESCE(website_url, 'http://www.activateyourimpact.com') WHERE lower(email) = 'sara@activateyourimpact.com';
UPDATE public.chamber_members SET membership_type = 'Silver', website_url = COALESCE(website_url, 'http://www.torinoramen.com') WHERE lower(email) = 'info@torinoramen.com';
UPDATE public.chamber_members SET membership_type = 'Silver', website_url = COALESCE(website_url, 'http://www.resourcewellnessllc.com') WHERE lower(email) = 'michellebobier@me.com';
UPDATE public.chamber_members SET membership_type = 'Silver', website_url = COALESCE(website_url, 'http://crowndentalclub.com') WHERE lower(email) = 'dr.scott@crowndentalclub.com';
UPDATE public.chamber_members SET membership_type = 'Basic' WHERE lower(email) = 'glenview@thecoderschool.com';
UPDATE public.chamber_members SET membership_type = 'Silver', website_url = COALESCE(website_url, 'https://polkofflaw.com/') WHERE lower(email) = 'mpolkoff@polkofflaw.com';
UPDATE public.chamber_members SET membership_type = 'Chamber of Commerce' WHERE lower(email) = 'director@wngchamber.com';
UPDATE public.chamber_members SET membership_type = 'Basic', website_url = COALESCE(website_url, 'http://www.interactive-speech.com') WHERE lower(email) = 'connieomtchicago@gmail.com';
UPDATE public.chamber_members SET membership_type = 'Non-Profit', website_url = COALESCE(website_url, 'http://www.wrbsprincipal.com') WHERE lower(email) = 'bill.springer@wrbsprincipal.com';
UPDATE public.chamber_members SET membership_type = 'Basic', website_url = COALESCE(website_url, 'http://www.wrbsprincipal.com') WHERE lower(email) = 'bill.springer@wrbsprincipal.com';
